#!/usr/bin/env python3

import json
import sys

MANIFEST = "custom_components/check_weather/manifest.json"


def main(version):
    # Read the manifest file
    with open(MANIFEST, "r") as file:
        data = json.load(file)

    # Update the version
    data["version"] = version.replace("v", "")

    # Write the manifest file
    with open(MANIFEST, "w") as file:
        json.dump(data, file, indent=2)


if __name__ == "__main__":
    if len(sys.argv) > 1:
        version = sys.argv[1]
        main(version)
    else:
        print("Please provide a version argument.")
